#pragma once

#define SINGLETONLOG_VER_MAJOR 0
#define SINGLETONLOG_VER_MINOR 9
#define SINGLETONLOG_VER_PATCH 0

#define SINGLETONLOG_VERSION (SINGLETONLOG_VER_MAJOR * 10000 + SINGLETONLOG_VER_MINOR * 100 + SINGLETONLOG_VER_PATCH)